/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 static/models/MrMan.glb --transform 
Files: static/models/MrMan.glb [17.34MB] > /home/persist/mine/repos/bs/Tower Defense/neo/MrMan-transformed.glb [1.51MB] (91%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene } = useGLTF('/MrMan-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials, animations } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[0.032, 1.518, -0.086]} scale={1.714}>
          <primitive object={nodes.Torso} />
          <group name="Head_1">
            <skinnedMesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials['Metal.001']} skeleton={nodes.Cylinder003.skeleton} />
            <skinnedMesh name="Cylinder003_1" geometry={nodes.Cylinder003_1.geometry} material={materials['Material.001']} skeleton={nodes.Cylinder003_1.skeleton} />
            <skinnedMesh name="Cylinder003_2" geometry={nodes.Cylinder003_2.geometry} material={materials['Metal.011']} skeleton={nodes.Cylinder003_2.skeleton} />
            <skinnedMesh name="Cylinder003_3" geometry={nodes.Cylinder003_3.geometry} material={materials['Metal.009']} skeleton={nodes.Cylinder003_3.skeleton} />
            <skinnedMesh name="Cylinder003_4" geometry={nodes.Cylinder003_4.geometry} material={materials['Iron Metal']} skeleton={nodes.Cylinder003_4.skeleton} />
          </group>
        </group>
        <primitive object={nodes.neutral_bone} />
      </group>
    </group>
  )
}

useGLTF.preload('/MrMan-transformed.glb')
