<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /home/persist/mine/repos/bs/TowerDefense/neo/static/models/MrMan.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import { forwardEventHandlers, T, type Events, type Props, type Slots } from '@threlte/core';
  import { useGltf, useGltfAnimations } from '@threlte/extras';
  import type * as THREE from 'three';
  import { Group } from 'three';

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type ActionName = 'ArmatureAction.001' | 'HeadAction'
  type GLTFResult = {
    nodes: {
      Cylinder003: THREE.SkinnedMesh
      Cylinder003_1: THREE.SkinnedMesh
      Cylinder003_2: THREE.SkinnedMesh
      Cylinder003_3: THREE.SkinnedMesh
      Cylinder003_4: THREE.SkinnedMesh
      Torso: THREE.Bone
      neutral_bone: THREE.Bone
    }
    materials: {
      ['Metal.001']: THREE.MeshStandardMaterial
      ['Material.001']: THREE.MeshStandardMaterial
      ['Metal.011']: THREE.MeshStandardMaterial
      ['Metal.009']: THREE.MeshStandardMaterial
      ['Iron Metal']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/MrMan.glb')
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="Armature" position={[0.03, 1.52, -0.09]} scale={1.71}>
        <T is={gltf.nodes.Torso} />
        <T is={gltf.nodes.neutral_bone} />
        <T.Group name="Head_1">
          <T.SkinnedMesh
            name="Cylinder003"
            geometry={gltf.nodes.Cylinder003.geometry}
            material={gltf.materials['Metal.001']}
            skeleton={gltf.nodes.Cylinder003.skeleton}
          />
          <T.SkinnedMesh
            name="Cylinder003_1"
            geometry={gltf.nodes.Cylinder003_1.geometry}
            material={gltf.materials['Material.001']}
            skeleton={gltf.nodes.Cylinder003_1.skeleton}
          />
          <T.SkinnedMesh
            name="Cylinder003_2"
            geometry={gltf.nodes.Cylinder003_2.geometry}
            material={gltf.materials['Metal.011']}
            skeleton={gltf.nodes.Cylinder003_2.skeleton}
          />
          <T.SkinnedMesh
            name="Cylinder003_3"
            geometry={gltf.nodes.Cylinder003_3.geometry}
            material={gltf.materials['Metal.009']}
            skeleton={gltf.nodes.Cylinder003_3.skeleton}
          />
          <T.SkinnedMesh
            name="Cylinder003_4"
            geometry={gltf.nodes.Cylinder003_4.geometry}
            material={gltf.materials['Iron Metal']}
            skeleton={gltf.nodes.Cylinder003_4.skeleton}
          />
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
